<a href="https://colab.research.google.com/github/sofaemha/upstegal/blob/main/Semester%206/Kriptografi/Tugas%2027-3-2025/Kriptografi_M1-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas Kriptografi
> Dosen : Bambang Sugiarto, M.Kom
>
> Mahasiswa : Sofa Machabba Haeta
>
> NPM : 6622600044
>
> Kelas / Semester : 6 / B


In [765]:
from itertools import chain
import numpy as np
import math

## 1.	Columnar Cipher

### Enkripsi

#### Langkah Pertama
Mengidentifikasi teks yang akan dienkripsi beserta kata kunci yang digunakan. Jika melihat soal, teks yang harus dienkripsi adalah “RAHASIA NEGARA” dengan kata kunci “KEAMANAN”.

In [766]:
columnar_text = "RAHASIA NEGARA"
columnar_key = "KEAMANAN"

#### Langkah kedua
Menentukan panjang kunci yang digunakan, dalam hal ini adalah “KEAMANAN” yang memiliki panjang 8 huruf

In [767]:
columnar_text_length = len(columnar_text)
columnar_key_length = len(columnar_key)
columnar_row = math.ceil(columnar_text_length / columnar_key_length)
columnar_space = columnar_text_length / columnar_key_length % 1 > 0

#### Langkah Ketiga
Menulis teks ke dalam sebuah tabel dengan banyaknya kolom sesuai dengan panjang kunci. Jangan lupa untuk mengubah nomor urut pada bagian atas terlebih dahulu. Sehingga menjadi seperti pada tabel berikut :

In [768]:
def fn_columnar_encrypt_step_1():
  step_1 = list(columnar_text)
  if columnar_space:
    for i in range(columnar_row): step_1.append(" ")

  step_2 = np.array(step_1)
  step_3 = step_2.reshape(columnar_row, columnar_key_length)

  step_4 = [str(value) for value in list(range(1, columnar_key_length+1))]
  one, two, three, four, five, six, seven, eight = step_4

  step_5 = np.array(step_4)
  step_6 = np.array([six, four, seven, one, five, three, two, eight])
  step_7 = np.vstack([step_6, step_3])
  return step_7

for columnar_value in fn_columnar_encrypt_step_1():
  print(columnar_value)

['6' '4' '7' '1' '5' '3' '2' '8']
['R' 'A' 'H' 'A' 'S' 'I' 'A' ' ']
['N' 'E' 'G' 'A' 'R' 'A' ' ' ' ']


#### Langkah Keempat
Mengurutkan nomor pada bagian atas tabel. Sehingga menjadi seperti pada tabel berikut :

In [769]:
def fn_columnar_encrypt_step_2():
  step_1 = fn_columnar_encrypt_step_1()
  order, top, bottom = step_1
  step_2 = np.array([top, bottom])
  step_3 = np.transpose(step_2).tolist()
  six, four, seven, one, five, three, two, eight = step_3

  step_4 = np.array([one, two, three, four, five, six, seven, eight])
  step_5 = np.transpose(step_4)
  step_6 = np.array(sorted(order, key=int))
  step_7 = np.vstack([step_6, step_5])
  return step_7

print(fn_columnar_encrypt_step_2())

[['1' '2' '3' '4' '5' '6' '7' '8']
 ['A' 'A' 'I' 'A' 'S' 'R' 'H' ' ']
 ['A' ' ' 'A' 'E' 'R' 'N' 'G' ' ']]


#### Langkah Kelima
Menulis teks pada tabel sesuai dengan nomor urut yang ditulis dari atas ke bawah. Jika melihat tabel pada langkah keempat, maka akan menjadi teks “AAA IAAESRRNHG  ”

In [770]:
def fn_columnar_encrypt_step_3():
  step_1 = fn_columnar_encrypt_step_2()
  order, top, bottom = step_1
  step_2 = np.array([top, bottom])
  step_3 = np.transpose(step_2).tolist()
  step_4 = ''.join([''.join(map(str, item)) if isinstance(item, list) else str(item) for item in step_3]).strip()
  return step_4

print(f"'{fn_columnar_encrypt_step_3()}'")

'AAA IAAESRRNHG'


## 2.	Affine Cipher

### Enkripsi

#### Langkah Pertama
Mengidentifikasi teks yang akan dienkripsi beserta kata kunci yang digunakan. Jika melihat soal, teks yang harus dienkripsi adalah “PESAN” dengan kata kunci (a/salt) 5, dan (b/offsets) 8.

In [771]:
affine_text = "PESAN"

In [772]:
affine_salt = 5
affine_offset = 8
affine_max_char = 26
affine_char_diff = 65

#### Langkah Kedua
Mengubah teks menjadi angka numerik dengan rumus jika A adalah 0 (nol), dan Z adalah 25 (dua puluh lima). Sehingga teks [ P, E, S, A, N ] akan berubah menjadi [ 15, 4, 18, 0, 13 ].

In [773]:
def fn_affine_encrypt_step_1():
  step_1 = list(affine_text)
  return step_1

print(fn_affine_encrypt_step_1())


['P', 'E', 'S', 'A', 'N']


In [774]:
affine_log_encrypt_step_2 = []

def fn_affine_encrypt_step_2():
  step_1 = fn_affine_encrypt_step_1()
  step_2 = [value - affine_char_diff for value in list(map(ord, step_1))]

  for affine_index, affine_value in enumerate(step_1):
    log_entry = f"{step_1[affine_index]}: {ord(affine_value)-affine_char_diff}"
    affine_log_encrypt_step_2.append(log_entry)

  return step_2

print(f"{fn_affine_encrypt_step_2()}\n")

for entry in affine_log_encrypt_step_2:
  print(entry)

[15, 4, 18, 0, 13]

P: 15
E: 4
S: 18
A: 0
N: 13


#### Langkah Ketiga
Melakukan enkripsi dengan rumus : $ E_{(x)}=(a\ast x+b)\ \%\ c$

Apabila salt (a) adalah 5, offsets (b) adalah 8, dan jumlah huruf (c) adalah 26. Maka akan menjadi sebagai berikut :

In [775]:
affine_log_encrypt_step_3 = []
affine_log_encrypt_step_3_sub_step_5 = []

def fn_affine_encrypt_step_3():
  step_1 = fn_affine_encrypt_step_1()
  step_2 = fn_affine_encrypt_step_2()
  step_3 = [((affine_value * affine_salt + affine_offset) % affine_max_char) for affine_value in step_2]
  step_7 = []

  for affine_index, affine_value in enumerate(step_2):
    step_4 = affine_value * affine_salt
    step_5 = step_4 + affine_offset
    step_6 = step_5 % affine_max_char
    step_7.append(step_5)
    log_entry = f"{step_1[affine_index]}: ({affine_value} * {affine_salt} + {affine_offset}) = ({step_4} + {affine_offset}) % {affine_max_char} = {step_5} % {affine_max_char} = {step_6}"
    affine_log_encrypt_step_3.append(log_entry)

  affine_log_encrypt_step_3_sub_step_5.extend(step_7)
  return step_3

print(f"{fn_affine_encrypt_step_3()}\n")

for entry in affine_log_encrypt_step_3:
  print(entry)

[5, 2, 20, 8, 21]

P: (15 * 5 + 8) = (75 + 8) % 26 = 83 % 26 = 5
E: (4 * 5 + 8) = (20 + 8) % 26 = 28 % 26 = 2
S: (18 * 5 + 8) = (90 + 8) % 26 = 98 % 26 = 20
A: (0 * 5 + 8) = (0 + 8) % 26 = 8 % 26 = 8
N: (13 * 5 + 8) = (65 + 8) % 26 = 73 % 26 = 21


#### Langkah Keempat
Berdasarkan hasil visualisasi modulus pada langkah ketiga dapat ditarik kesimpulan bahwa nilai awal dari teks yakni [ 15, 4, 18, 0, 13 ], akan berubah menjadi [ 5, 2, 20, 8, 21] setelah melewati proses enkripsi.

##### Visualisasi Modulus
Menggunakan rumus $ M_{(A)}=A-P_{(n)} $, dimana $ A $ adalah $ (x \ast a + b) $ dan $ P_{(n)} $ adalah perkalian antara jumlah huruf (c) dengan iterasi ke-n. Alasan kenapa saya menggunakan cara ini, agar mudah melakukan presentasi visual, daripada harus menebak berapa angka yang jika dikalikan dengan 26 hasilnya mendekati dan tidak melebihi $ A $. Sehingga menjadi seperti pada tabel berikut :

In [776]:
affine_log_encrypt_step_4_sub_step_1 = []
affine_log_encrypt_step_4_sub_step_2 = fn_affine_encrypt_step_1()

def fn_affine_encrypt_step_4():

  step_1 = affine_log_encrypt_step_4_sub_step_2
  step_2 = affine_log_encrypt_step_3_sub_step_5
  chunk_p, chunk_e, chunk_s, chunk_a, chunk_n = step_2
  step_3 = {
    "P": lambda array: fn_step_1(text_p, array),
    "E": lambda array: fn_step_1(text_e, array),
    "S": lambda array: fn_step_1(text_s, array),
    "A": lambda array: fn_step_1(text_a, array),
    "N": lambda array: fn_step_1(text_n, array),
  }

  text_p = [chunk_p]
  text_e = [chunk_e]
  text_s = [chunk_s]
  text_a = [chunk_a]
  text_n = [chunk_n]

  def fn_step_1(value, *array):
    sub_step_1 = f"{array[-1]}"
    sub_step_2 = value[-1] - (affine_max_char * 1)
    if (sub_step_2 >= 0):
      fn_step_2(sub_step_1, sub_step_2)
      fn_step_1([sub_step_2], array[-1])

  def fn_step_2(index, value):
      if (index == "P"): text_p.append(value)
      if (index == "E"): text_e.append(value)
      if (index == "S"): text_s.append(value)
      if (index == "A"): text_a.append(value)
      if (index == "N"): text_n.append(value)

  for affine_value in step_1:
    step_3.get(affine_value)(affine_value)

  return [ text_p, text_e, text_s, text_a, text_n ]

affine_log_encrypt_step_4_sub_step_1.extend(fn_affine_encrypt_step_4())

for affine_index, affine_value in enumerate(affine_log_encrypt_step_4_sub_step_1):
  print(f"{affine_log_encrypt_step_4_sub_step_2[affine_index]}: {affine_value}")

P: [83, 57, 31, 5]
E: [28, 2]
S: [98, 72, 46, 20]
A: [8]
N: [73, 47, 21]


<table>
  <tr>
    <td rowspan="2">#</td>
    <td rowspan="2">A</td>
    <td colspan="3">
      <center>n</center>
    </td>
  </tr>
  <tr>
    <td>
      <center>1</center>
    </td>
    <td>
      <center>2</center>
    </td>
    <td>
      <center>3</center>
    </td>
  </tr>
  <tr>
    <td>P</td>
    <td>83</td>
    <td>83-(26*1)</td>
    <td>83-(26*2)</td>
    <td>83-(26*3)</td>
  </tr>
  <tr>
    <td>E</td>
    <td>28</td>
    <td>28-(26*1)</td>
    <td>28-(26*2)</td>
    <td>28-(26*3)</td>
  </tr>
  <tr>
    <td>S</td>
    <td>98</td>
    <td>98-(26*1)</td>
    <td>98-(26*2)</td>
    <td>98-(26*3)</td>
  </tr>
  <tr>
    <td>A</td>
    <td>8</td>
    <td>8-(26*1)</td>
    <td>8-(26*2)</td>
    <td>8-(26*3)</td>
  </tr>
  <tr>
    <td>N</td>
    <td>73</td>
    <td>73-(26*1)</td>
    <td>73-(26*2)</td>
    <td>73-(26*3)</td>
  </tr>
</table>

<table>
  <tr>
    <td rowspan="2">#</td>
    <td rowspan="2">A</td>
    <td colspan="3">
      <center>n</center>
    </td>
  </tr>
  <tr>
    <td>
      <center>1</center>
    </td>
    <td>
      <center>2</center>
    </td>
    <td>
      <center>3</center>
    </td>
  </tr>
  <tr>
    <td>P</td>
    <td>83</td>
    <td>83-26</td>
    <td>83-52</td>
    <td>83-78</td>
  </tr>
  <tr>
    <td>E</td>
    <td>28</td>
    <td>28-26</td>
    <td>28-52</td>
    <td>28-78</td>
  </tr>
  <tr>
    <td>S</td>
    <td>98</td>
    <td>98-26</td>
    <td>98-52</td>
    <td>98-78</td>
  </tr>
  <tr>
    <td>A</td>
    <td>8</td>
    <td>8-26</td>
    <td>8-52</td>
    <td>8-78</td>
  </tr>
  <tr>
    <td>N</td>
    <td>73</td>
    <td>73-26</td>
    <td>73-52</td>
    <td>73-78</td>
  </tr>
</table>

<table>
  <tr>
    <td rowspan="2">#</td>
    <td rowspan="2">A</td>
    <td colspan="3">
      <center>n</center>
    </td>
  </tr>
  <tr>
    <td>
      <center>1</center>
    </td>
    <td>
      <center>2</center>
    </td>
    <td>
      <center>3</center>
    </td>
  </tr>
  <tr>
    <td>P</td>
    <td>83</td>
    <td>57</td>
    <td>31</td>
    <td>5</td>
  </tr>
  <tr>
    <td>E</td>
    <td>28</td>
    <td>2</td>
    <td>-24</td>
    <td>-50</td>
  </tr>
  <tr>
    <td>S</td>
    <td>98</td>
    <td>72</td>
    <td>46</td>
    <td>20</td>
  </tr>
  <tr>
    <td>A</td>
    <td>8</td>
    <td>-18</td>
    <td>-44</td>
    <td>-70</td>
  </tr>
  <tr>
    <td>N</td>
    <td>73</td>
    <td>47</td>
    <td>21</td>
    <td>-5</td>
  </tr>
</table>

##### Kesimpulan
Berdasarkan tabel di atas, kotak dengan warna kuning menandakan bahwa nilai dari $ M(A) $ berdasarkan iterasi ke-n sudah melebihi 0 (nol) dan dinyatakan tidak valid karena menghasilkan sisa hasil bagi dengan nilai negatif. Oleh karena itu, nilai $ M(A) $ yang bisa diambil adalah iterasi sebelum sisa hasil bagi menjadi negatif, yang ditandai dengan kotak berwarna hijau. Akan tetapi, jika sejak iterasi pertama sisa hasil bagi sudah bernilai negatif, maka nilai dari $ M(A) $ adalah $ A $.

#### Langkah Kelima
Mengubah angka numerik sesuai dengan rumus pada langkah kedua, sehingga menjadi [ F, C, U, I, V ] atau “FCUIV”.

In [777]:
affine_log_encrypt_step_5 = []

def fn_affine_encrypt_step_5():
  step_1 = fn_affine_encrypt_step_1()
  step_2 = fn_affine_encrypt_step_2()
  step_3 = fn_affine_encrypt_step_3()
  step_4 = [chr(value + affine_char_diff) for value in step_3]

  for affine_index, affine_value in enumerate(step_4):
    log_entry = f"{step_1[affine_index]}: {affine_value}"
    affine_log_encrypt_step_5.append(log_entry)

  return step_4

print(f"{fn_affine_encrypt_step_5()}\n")

for entry in affine_log_encrypt_step_5:
  print(entry)

['F', 'C', 'U', 'I', 'V']

P: F
E: C
S: U
A: I
N: V


### Dekripsi

#### Langkah Pertama
Mengubah teks menjadi angka numerik dengan rumus jika A adalah 0 (nol), dan Z adalah 25 (dua puluh lima). Sehingga teks [ F, C, U, I, V ] akan berubah menjadi [ 5, 2, 20, 8, 21].

In [778]:
affine_log_decrypt_step_1 = []

def fn_affine_decrypt_step_1():
  step_1 = fn_affine_encrypt_step_5()
  step_2 = [value - affine_char_diff for value in list(map(ord, step_1))]

  for affine_index, affine_value in enumerate(step_1):
    log_entry = f"{step_1[affine_index]}: {ord(affine_value)-affine_char_diff}"
    affine_log_decrypt_step_1.append(log_entry)

  return step_2

print(f"{fn_affine_decrypt_step_1()}\n")

for entry in affine_log_decrypt_step_1:
  print(entry)

[5, 2, 20, 8, 21]

F: 5
C: 2
U: 20
I: 8
V: 21


#### Langkah Kedua

Mengidentifikasi nilai dari $a^{-1}$ yang terdapat pada rumus $D_{(x)}=a^{-1}(x-b)\ \% \ c$. Apabila $a^{-1}$ adalah bilangan relatif prima antara salt (a) dan jumlah huruf (c) yang merujuk pada angka berapa yang jika dikalikan dengan (a) dan dimodulus oleh (c) menghasilkan nilai 1 (satu), atau dapat ditulis dengan rumus $P_{(n)}=a * n \ \% \ c$. Sehingga bisa menjadi seperti pada hasil berikut :

In [779]:
affine_log_decrypt_step_2_sub_step_2 = []
affine_log_decrypt_step_2_sub_step_3 = []

def fn_affine_decrypt_step_2():
  fn_step_1 = lambda affine_value: affine_value * affine_salt
  fn_step_2 = lambda affine_value: fn_step_1(affine_value) % affine_max_char
  step_1 = [1]
  step_2 = [fn_step_2(step_1[0])]

  while step_2[-1] != 1:
    step_1.append(step_1[-1]+1)
    step_2.append(fn_step_2(step_1[-1]))

  for affine_value in step_1:
    step_3 = f"(n = {affine_value}) = {affine_salt} * {affine_value} % {affine_max_char} = {fn_step_1(affine_value)} % {affine_max_char} = {fn_step_2(affine_value)}"
    affine_log_decrypt_step_2_sub_step_3.append(step_3)

  affine_log_decrypt_step_2_sub_step_2.extend(step_2)
  step_3 = step_1[-1]
  return step_3

print(f"{fn_affine_decrypt_step_2()}\n")
print(f"{affine_log_decrypt_step_2_sub_step_2}\n")

for entry in affine_log_decrypt_step_2_sub_step_3:
  print(entry)

21

[5, 10, 15, 20, 25, 4, 9, 14, 19, 24, 3, 8, 13, 18, 23, 2, 7, 12, 17, 22, 1]

(n = 1) = 5 * 1 % 26 = 5 % 26 = 5
(n = 2) = 5 * 2 % 26 = 10 % 26 = 10
(n = 3) = 5 * 3 % 26 = 15 % 26 = 15
(n = 4) = 5 * 4 % 26 = 20 % 26 = 20
(n = 5) = 5 * 5 % 26 = 25 % 26 = 25
(n = 6) = 5 * 6 % 26 = 30 % 26 = 4
(n = 7) = 5 * 7 % 26 = 35 % 26 = 9
(n = 8) = 5 * 8 % 26 = 40 % 26 = 14
(n = 9) = 5 * 9 % 26 = 45 % 26 = 19
(n = 10) = 5 * 10 % 26 = 50 % 26 = 24
(n = 11) = 5 * 11 % 26 = 55 % 26 = 3
(n = 12) = 5 * 12 % 26 = 60 % 26 = 8
(n = 13) = 5 * 13 % 26 = 65 % 26 = 13
(n = 14) = 5 * 14 % 26 = 70 % 26 = 18
(n = 15) = 5 * 15 % 26 = 75 % 26 = 23
(n = 16) = 5 * 16 % 26 = 80 % 26 = 2
(n = 17) = 5 * 17 % 26 = 85 % 26 = 7
(n = 18) = 5 * 18 % 26 = 90 % 26 = 12
(n = 19) = 5 * 19 % 26 = 95 % 26 = 17
(n = 20) = 5 * 20 % 26 = 100 % 26 = 22
(n = 21) = 5 * 21 % 26 = 105 % 26 = 1


Berdasarkan perhitungan di atas, dapat disimpulkan bahwa nilai dari $a^{-1}$ adalah 21.

#### Langkah Ketiga
Melakukan dekripsi sesuai dengan rumus pada langkah pertama, apabila  offsets (b) adalah 8, dan jumlah huruf (c) adalah 26. Sehingga menjadi seperti pada hasil berikut :

In [780]:
affine_log_decrypt_step_3 = []
affine_log_decrypt_step_3_sub_step_6 = []

def fn_affine_decrypt_step_3():
  step_1 = fn_affine_encrypt_step_5()
  step_2 = fn_affine_decrypt_step_1()
  step_3 = fn_affine_decrypt_step_2()
  step_4 = [(step_3 * (value - affine_offset)) % affine_max_char for value in step_2]
  step_8 = []

  for affine_index, affine_value in enumerate(step_2):
    step_5 = affine_value - affine_offset
    step_6 = step_5 * step_3
    step_7 = step_6 % affine_max_char
    step_8.append(step_6)
    log_entry = f"{step_1[affine_index]} : ({step_3} * ({affine_value} - {affine_offset})) % {affine_max_char} = ({step_3} * {step_5}) % {affine_max_char} = {step_6} % {affine_max_char} = {step_7}"
    affine_log_decrypt_step_3.append(log_entry)

  affine_log_decrypt_step_3_sub_step_6.extend(step_8)
  return step_4

print(f"{fn_affine_decrypt_step_3()}\n")
for entry in affine_log_decrypt_step_3:
  print(entry)

[15, 4, 18, 0, 13]

F : (21 * (5 - 8)) % 26 = (21 * -3) % 26 = -63 % 26 = 15
C : (21 * (2 - 8)) % 26 = (21 * -6) % 26 = -126 % 26 = 4
U : (21 * (20 - 8)) % 26 = (21 * 12) % 26 = 252 % 26 = 18
I : (21 * (8 - 8)) % 26 = (21 * 0) % 26 = 0 % 26 = 0
V : (21 * (21 - 8)) % 26 = (21 * 13) % 26 = 273 % 26 = 13


#### Langkah Kelima
Mengubah angka numerik sesuai dengan rumus pada langkah kedua, sehingga menjadi [ P, E, S, A, N ] atau “PESAN”.

In [781]:
affine_log_decrypt_step_5 = []

def fn_affine_decrypt_step_5():
  step_1 = fn_affine_encrypt_step_5()
  step_2 = fn_affine_decrypt_step_3()
  step_3 = [chr(value + affine_char_diff) for value in step_2]

  for affine_index, affine_value in enumerate(step_3):
    log_entry = f"{step_1[affine_index]}: {affine_value}"
    affine_log_decrypt_step_5.append(log_entry)
  return step_3

print(f"{fn_affine_decrypt_step_5()}\n")
for entry in affine_log_decrypt_step_5:
  print(entry)

['P', 'E', 'S', 'A', 'N']

F: P
C: E
U: S
I: A
V: N


## 3.	Hill Cipher

### Enkripsi

#### Langkah Pertama
Mengidentifikasi teks yang akan dienkripsi beserta kata kunci yang digunakan. Jika melihat soal, teks yang harus dienkripsi adalah “SAYA” dengan kata kunci (key/salt) CBDE

In [782]:
hill_text = "SAYA"
hill_key = "CBDE"
hill_slice = 2
hill_max_char = 26
hill_char_diff = 65

In [783]:
def fn_hill_encrypt_step_1():
  step_1 = list(hill_text)
  return step_1

print(fn_hill_encrypt_step_1())

['S', 'A', 'Y', 'A']


In [784]:
def fn_hill_encrypt_step_2():
  step_1 = list(hill_key)
  return step_1

print(fn_hill_encrypt_step_2())

['C', 'B', 'D', 'E']


#### Langkah Kedua
Mengubah teks menjadi angka numerik dengan rumus jika A adalah 0 (nol), dan Z adalah 25 (dua puluh lima). Sehingga teks [ S, A, Y, A ] akan berubah menjadi [ 18, 0, 24, 0 ].

In [785]:
hill_log_encrypt_step_3 = []

def fn_hill_encrypt_step_3():
  step_1 = fn_hill_encrypt_step_1()
  step_2 = [value - hill_char_diff for value in list(map(ord, hill_text))]
  step_3 = [step_2[value : value + hill_slice] for value in range(0, len(step_2), hill_slice)]
  step_4 = np.matrix(step_3)

  for hill_index, hill_value in enumerate(step_1):
    log_entry = f"{step_1[hill_index]}: {ord(hill_value)-hill_char_diff}"
    hill_log_encrypt_step_3.append(log_entry)

  return step_4

print(f"{fn_hill_encrypt_step_3()}\n")
for entry in hill_log_encrypt_step_3:
  print(entry)

[[18  0]
 [24  0]]

S: 18
A: 0
Y: 24
A: 0


#### Langkah Ketiga
Mengubah kata kunci menjadi angka numerik dengan rumus jika A adalah 0 (nol), dan Z adalah 25 (dua puluh lima). Sehingga teks [ C, B, D, E ] akan berubah menjadi [ 2, 1, 3, 4 ].

In [786]:
hill_log_encrypt_step_4 = []

def fn_hill_encrypt_step_4():
  step_1 = fn_hill_encrypt_step_2()
  step_2 = [value - hill_char_diff for value in list(map(ord, step_1))]
  step_3 = [step_2[value : value + hill_slice] for value in range(0, len(step_2), hill_slice)]
  step_4 = np.matrix(step_3)

  for hill_index, hill_value in enumerate(step_1):
    log_entry = f"{step_1[hill_index]}: {ord(hill_value)-hill_char_diff}"
    hill_log_encrypt_step_4.append(log_entry)

  return step_4

print(f"{fn_hill_encrypt_step_4()}\n")
for entry in hill_log_encrypt_step_4:
  print(entry)

[[2 1]
 [3 4]]

C: 2
B: 1
D: 3
E: 4


Langkah keempat adalah melakukan enkripsi dengan rumus :

$$
E_{(x,\ y)}^n=\ (n_{(a,c)}\ *\ x)\ +\ (n_{(b,d)}\ *\ y)\ %\ z
$$

Keterangan :
*   $E_{(x,y)}^n$ adalah enkripsi data berdasarkan baris ke-n dengan kolom x dan y
*   $n_{(a,c)}$ adalah baris ke-n dimana n adalah a atau c pada matrix (2x2)
*   $n_{(b,d)}$ adalah baris ke-n dimana n adalah b atau d pada matrix (2x2)
*   $x$ adalah baris bagian atas pada matrix (1x2)
*   $y$ adalah baris bagian bawah pada matrix (1x2)
*   $z$ adalah jumlah huruf yakni 26

Sehingga menjadi seperti pada kode berikut :






In [787]:
hill_log_encrypt_step_5_sub_step_6 = []
hill_log_encrypt_step_5_sub_step_8 = []

def fn_hill_encrypt_step_5():
  step_1 = fn_hill_encrypt_step_3()
  step_2 = fn_hill_encrypt_step_4()

  a, b, c, d = list(chain.from_iterable(step_1.tolist()))
  p, q, r, s = list(chain.from_iterable(step_2.tolist()))

  pair_left = [a, c]
  pair_right = [b, d]

  top_left = (a * p) + (b * q)
  top_right = (a * r) + (b * s)
  bottom_left = (c * p) + (d * q)
  bottom_right = (c * r) + (d * s)

  step_3 = [top_left, top_right, bottom_left, bottom_right]
  step_4 = [step_3[value : value + hill_slice] for value in range(0, len(step_3), hill_slice)]
  step_5 = np.array(step_4)
  step_6 = step_5 % hill_max_char
  step_7 = list(chain.from_iterable(step_6.tolist()))

  for hill_index in range(hill_slice):
    sub_top_name = "c" if hill_index > 0 else "a"
    sub_bottom_name = "d" if hill_index > 0 else "b"

    sub_top_left_step_1 = p * pair_left[hill_index]
    sub_bottom_left_step_1 = r * pair_left[hill_index]
    sub_top_right_step_1 = q * pair_right[hill_index]
    sub_bottom_right_step_1 = s * pair_right[hill_index]

    sub_top_step_2 = sub_top_left_step_1 + sub_top_right_step_1
    sub_bottom_step_2 = sub_bottom_left_step_1 + sub_bottom_right_step_1

    sub_top_step_3 = sub_top_step_2 % hill_max_char
    sub_bottom_step_3 = sub_bottom_step_2 % hill_max_char

    sub_step_top = f"{sub_top_name}: ({p} * {pair_left[hill_index]}) + ({q} * {pair_right[hill_index]}) % {hill_max_char} = ({sub_top_left_step_1} + {sub_top_right_step_1}) % {hill_max_char} = {sub_top_step_2} % {hill_max_char} = {sub_top_step_3}"
    sub_step_bottom = f"{sub_bottom_name}: ({r} * {pair_left[hill_index]}) + ({s} * {pair_right[hill_index]}) % {hill_max_char} = ({sub_bottom_left_step_1} + {sub_bottom_right_step_1}) % {hill_max_char} = {sub_bottom_step_2} % {hill_max_char} = {sub_bottom_step_3}"

    hill_log_encrypt_step_5_sub_step_8.extend([sub_step_top])
    hill_log_encrypt_step_5_sub_step_8.extend([sub_step_bottom])

  hill_log_encrypt_step_5_sub_step_6.extend(step_6)
  return step_7

fn_hill_encrypt_step_5()
print(f"{np.matrix(hill_log_encrypt_step_5_sub_step_6)}\n")

for entry in hill_log_encrypt_step_5_sub_step_8:
  print(entry)

[[10  2]
 [22 20]]

a: (2 * 18) + (1 * 0) % 26 = (36 + 0) % 26 = 36 % 26 = 10
b: (3 * 18) + (4 * 0) % 26 = (54 + 0) % 26 = 54 % 26 = 2
c: (2 * 24) + (1 * 0) % 26 = (48 + 0) % 26 = 48 % 26 = 22
d: (3 * 24) + (4 * 0) % 26 = (72 + 0) % 26 = 72 % 26 = 20


Berdasarkan tabel di atas, dapat disimpulkan bahwa hasil dari perkalian antara
[ [ 18, 24 ] [ 0, 0 ] ] dan [ 2, 1, 3, 4 ] adalah [ 10, 2, 22, 20 ].


#### Langkah Kelima
Mengubah angka numerik sesuai dengan rumus pada langkah kedua, sehingga menjadi [ K, C, W, U ] atau “KCWU”.

In [797]:
def fn_hill_encrypt_step_6():
  step_1 = fn_hill_encrypt_step_5()
  step_2 = [chr(value + hill_char_diff) for value in step_1]
  return step_2

hill_log_encrypt_step_6 = fn_hill_encrypt_step_6()

print(f"{hill_log_encrypt_step_6}\n")
for hill_index, hill_value in enumerate(hill_log_encrypt_step_6):
  print(f"{hill_text[hill_index]}: {hill_value}")

['K', 'C', 'W', 'U']

S: K
A: C
Y: W
A: U


### Dekripsi

---

#### Langkah Pertama
Mengidentifikasi teks yang akan dienkripsi beserta kata kunci yang digunakan. Jika melihat soal, teks yang harus didekripsi adalah “KCWU” dengan kata kunci (key/salt) CBDE.

#### Langkah Kedua
Mengubah teks menjadi angka numerik dengan rumus jika A adalah 0 (nol), dan Z adalah 25 (dua puluh lima). Sehingga teks [ K, C, W, U ] akan berubah menjadi [ 10, 2, 22, 20 ].


#### Langkah Ketiga
Mengubah kata kunci menjadi angka numerik dengan rumus jika A adalah 0 (nol), dan Z adalah 25 (dua puluh lima). Sehingga teks [ C, B, D, E ] akan berubah menjadi [ 2, 1, 3, 4 ].


#### Langkah Keempat
Mencari determinan pada kata kunci yang sudah menjadi matrix, dengan menggunakan kode berikut :

In [789]:
def fn_hill_decrypt_step_1():
  step_1 = fn_hill_encrypt_step_4()
  step_2 = round(np.linalg.det(step_1))
  return step_2

print(fn_hill_decrypt_step_1())

5


#### Langkah Kelima
Mencari invers pada kata kunci yang sudah menjadi matrix, dengan menggunakan kode berikut :

In [790]:
def fn_hill_decrypt_step_2():
  step_1 = fn_hill_encrypt_step_4()
  step_2 = step_1.tolist()
  step_3 = list(chain.from_iterable(step_2))
  a, b, c, d = step_3
  step_4 = np.array([d, -b, -c, a])
  step_5 = step_4.reshape(2, 2)
  return step_5

print(f"{fn_hill_decrypt_step_2()}\n")

[[ 4 -1]
 [-3  2]]



In [791]:
hill_log_decrypt_step_3_sub_step_2 = []
hill_log_decrypt_step_3_sub_step_3 = []

def fn_hill_decrypt_step_3():
  step_0 = fn_hill_decrypt_step_1()
  fn_step_1 = lambda hill_value: hill_value * step_0
  fn_step_2 = lambda hill_value: fn_step_1(hill_value) % hill_max_char
  step_1 = [1]
  step_2 = [fn_step_2(step_1[0])]

  while step_2[-1] != 1:
    step_1.append(step_1[-1]+1)
    step_2.append(fn_step_2(step_1[-1]))

  for hill_value in step_1:
    step_3 = f"(n = {hill_value}) = {step_0} * {hill_value} % {hill_max_char} = {fn_step_1(hill_value)} % {hill_max_char} = {fn_step_2(hill_value)}"
    hill_log_decrypt_step_3_sub_step_3.append(step_3)

  hill_log_decrypt_step_3_sub_step_2.extend(step_2)
  step_3 = step_1[-1]
  return step_3

print(f"{fn_hill_decrypt_step_3()}\n")
print(f"{hill_log_decrypt_step_3_sub_step_2}\n")

for entry in hill_log_decrypt_step_3_sub_step_3:
  print(entry)

21

[5, 10, 15, 20, 25, 4, 9, 14, 19, 24, 3, 8, 13, 18, 23, 2, 7, 12, 17, 22, 1]

(n = 1) = 5 * 1 % 26 = 5 % 26 = 5
(n = 2) = 5 * 2 % 26 = 10 % 26 = 10
(n = 3) = 5 * 3 % 26 = 15 % 26 = 15
(n = 4) = 5 * 4 % 26 = 20 % 26 = 20
(n = 5) = 5 * 5 % 26 = 25 % 26 = 25
(n = 6) = 5 * 6 % 26 = 30 % 26 = 4
(n = 7) = 5 * 7 % 26 = 35 % 26 = 9
(n = 8) = 5 * 8 % 26 = 40 % 26 = 14
(n = 9) = 5 * 9 % 26 = 45 % 26 = 19
(n = 10) = 5 * 10 % 26 = 50 % 26 = 24
(n = 11) = 5 * 11 % 26 = 55 % 26 = 3
(n = 12) = 5 * 12 % 26 = 60 % 26 = 8
(n = 13) = 5 * 13 % 26 = 65 % 26 = 13
(n = 14) = 5 * 14 % 26 = 70 % 26 = 18
(n = 15) = 5 * 15 % 26 = 75 % 26 = 23
(n = 16) = 5 * 16 % 26 = 80 % 26 = 2
(n = 17) = 5 * 17 % 26 = 85 % 26 = 7
(n = 18) = 5 * 18 % 26 = 90 % 26 = 12
(n = 19) = 5 * 19 % 26 = 95 % 26 = 17
(n = 20) = 5 * 20 % 26 = 100 % 26 = 22
(n = 21) = 5 * 21 % 26 = 105 % 26 = 1


In [792]:
hill_log_decrypt_step_4 = []

def fn_hill_decrypt_step_4():
  step_1 = fn_hill_decrypt_step_2()
  step_2 = fn_hill_decrypt_step_3()
  step_3 = np.dot(step_2, step_1)
  step_4 = list(chain.from_iterable(step_1.tolist()))
  step_5 = list(chain.from_iterable(step_3.tolist()))

  hill_log_decrypt_step_4.extend([f"K(i) = ({step_2} * {step_4}) % {hill_max_char}"])
  hill_log_decrypt_step_4.extend([f"K(i) = {step_5} % {hill_max_char}"])
  return step_3

print(f"{fn_hill_decrypt_step_4()}\n")
for entry in hill_log_decrypt_step_4:
  print(entry)

[[ 84 -21]
 [-63  42]]

K(i) = (21 * [4, -1, -3, 2]) % 26
K(i) = [84, -21, -63, 42] % 26


In [793]:
hill_log_decrypt_step_5 = []

def fn_hill_decrypt_step_5():
  step_1 = fn_hill_decrypt_step_4()
  step_2 = step_1 % hill_max_char
  step_3 = list(chain.from_iterable(step_1.tolist()))
  step_4 = list(chain.from_iterable(step_2.tolist()))

  hill_log_decrypt_step_5.extend([f"K(i) = {step_3} % {hill_max_char}"])
  hill_log_decrypt_step_5.extend([f"K(i) = {step_4}"])
  return step_2

print(f"{fn_hill_decrypt_step_5()}\n")
for entry in hill_log_decrypt_step_5:
  print(entry)

[[ 6  5]
 [15 16]]

K(i) = [84, -21, -63, 42] % 26
K(i) = [6, 5, 15, 16]


#### Langkah Keenam
Melakukan perkalian silang antara teks yang akan didekripsi dengan matrix kunci yang sudah melalui proses inverse. Ketika melakukan perkalian silang, nilai dari teks akan terbagi menjadi 2 (dua) bagian dengan ukuran matrix (1x2) yang diambil dari matrix (2x2). Setelah mengalami perubahan, barulah teks tersebut dikali silang dengan matrix kunci inverse, seperti pada kode berikut ini :

In [794]:
def fn_hill_decrypt_step_6():
  step_1 = fn_hill_encrypt_step_6()
  step_2 = [value - hill_char_diff for value in list(map(ord, step_1))]
  step_3 = np.matrix(step_2)
  step_4 = np.reshape(step_3, (2, 2))
  return step_4

print(f"{fn_hill_decrypt_step_6()}\n")

[[10  2]
 [22 20]]



In [795]:
hill_log_decrypt_step_7_sub_step_6 = []
hill_log_decrypt_step_7_sub_step_8 = []

def fn_hill_decrypt_step_7():
  step_1 = fn_hill_decrypt_step_5()
  step_2 = fn_hill_decrypt_step_6()

  a,b,c,d = list(chain.from_iterable(step_1.tolist()))
  p,q,r,s = list(chain.from_iterable(step_2.tolist()))

  pair_left = [a, c]
  pair_right = [b, d]

  top_left = (a * p) + (b * q)
  top_right = (a * r) + (b * s)
  bottom_left = (c * p) + (d * q)
  bottom_right = (c * r) + (d * s)

  step_3 = [top_left, bottom_left, top_right, bottom_right]
  step_4 = [step_3[value : value + hill_slice] for value in range(0, len(step_3), hill_slice)]
  step_5 = np.array(step_4)
  step_6 = step_5 % hill_max_char
  step_7 = list(chain.from_iterable(step_6.tolist()))

  for hill_index in range(hill_slice):
    sub_top_name = "b" if hill_index > 0 else "a"
    sub_bottom_name = "d" if hill_index > 0 else "c"

    sub_top_left_step_1 = p * pair_left[hill_index]
    sub_bottom_left_step_1 = r * pair_left[hill_index]
    sub_top_right_step_1 = q * pair_right[hill_index]
    sub_bottom_right_step_1 = s * pair_right[hill_index]

    sub_top_step_2 = sub_top_left_step_1 + sub_top_right_step_1
    sub_bottom_step_2 = sub_bottom_left_step_1 + sub_bottom_right_step_1

    sub_top_step_3 = sub_top_step_2 % hill_max_char
    sub_bottom_step_3 = sub_bottom_step_2 % hill_max_char

    sub_step_top = f"{sub_top_name}: ({p} * {pair_left[hill_index]}) + ({q} * {pair_right[hill_index]}) % {hill_max_char} = ({sub_top_left_step_1} + {sub_top_right_step_1}) % {hill_max_char} = {sub_top_step_2} % {hill_max_char} = {sub_top_step_3}"
    sub_step_bottom = f"{sub_bottom_name}: ({r} * {pair_left[hill_index]}) + ({s} * {pair_right[hill_index]}) % {hill_max_char} = ({sub_bottom_left_step_1} + {sub_bottom_right_step_1}) % {hill_max_char} = {sub_bottom_step_2} % {hill_max_char} = {sub_bottom_step_3}"

    hill_log_decrypt_step_7_sub_step_8.extend([sub_step_top])
    hill_log_decrypt_step_7_sub_step_8.extend([sub_step_bottom])

  hill_log_decrypt_step_7_sub_step_6.extend(step_6)
  return step_7

fn_hill_decrypt_step_7()
print(f"{np.matrix(hill_log_decrypt_step_7_sub_step_6)}\n")

for entry in hill_log_decrypt_step_7_sub_step_8:
  print(entry)

[[18  0]
 [24  0]]

a: (10 * 6) + (2 * 5) % 26 = (60 + 10) % 26 = 70 % 26 = 18
c: (22 * 6) + (20 * 5) % 26 = (132 + 100) % 26 = 232 % 26 = 24
b: (10 * 15) + (2 * 16) % 26 = (150 + 32) % 26 = 182 % 26 = 0
d: (22 * 15) + (20 * 16) % 26 = (330 + 320) % 26 = 650 % 26 = 0


#### Langkah Ketujuh
Mengubah angka numerik sesuai dengan rumus pada langkah kedua atau ketiga. Sehingga yang semula adalah [ 18, 0, 24, 0 ] menjadi [ S, A, Y, A ] atau “SAYA”, sehingga menjadi seperti berikut :

In [796]:
def fn_hill_decrypt_step_8():
  step_1 = fn_hill_decrypt_step_7()
  step_2 = [chr(value + hill_char_diff) for value in step_1]
  print(step_2)

fn_hill_decrypt_step_8()

['S', 'A', 'Y', 'A']
